import type { BankMaster, EmploymentType } from "@/types";

const ALL_EMP: EmploymentType[] = ['正社員', '公務員', '契約社員', 'パート・アルバイト', '自営業', 'その他'];
const STABLE_EMP: EmploymentType[] = ['正社員', '公務員', '契約社員'];
const REGULAR_EMP: EmploymentType[] = ['正社員', '公務員'];

export const BANKS: BankMaster[] = [
  // ── 変動金利 ────────────────────────────────────────────────────────────────

  {
    id: 'sbi_var',
    name: '住信SBIネット銀行',
    productName: 'ネット専用住宅ローン（変動）',
    productType: 'variable',
    rate: 0.320,
    danshin: '無料（全疾病保障付）',
    feeYen: 55000,
    guarantee: '不要',
    areas: ['全国'],
    minIncome: 200,
    minYearsEmployed: 1,
    allowedEmployments: ALL_EMP,
    maxLoanRatio: 7,
    features: ['全疾病保障が無料', '審査スピードが速い', 'ネット完結で手続き簡単'],
    jobChangeMonths: 0,
    selfEmployedYears: 2,
    corporateRepOk: true,
    contractOk: true,
    dispatchOk: false,
    foreignNationalOk: true,
    permanentResidencyRequired: false,
    incomeAggregationOk: true,
    pairLoanOk: true,
    carLoanImpact: '中',
    cardLoanImpact: '高',
    danshinTypes: ['一般団信（無料）', '全疾病保障（無料）', 'がん診断給付金（+0.10%）', 'がん100%保障（+0.20%）', '11疾病保障（+0.30%）'],
    zehDiscount: 0.050,
    longTermQualityDiscount: 0.050,
    webApplicationUrl: 'https://www.netbk.co.jp/contents/lineup/homeloan/',
    paperApplicationUrl: '',
    preScreeningDays: '最短3営業日',
    bridgeLoanSupport: 'unsupported',
    splitExecutionSupport: 'unsupported',
    landFirstLoanSupport: 'unsupported',
    buildingInterimSupport: 'unsupported',
    repaymentStartTiming: 'final',
    bridgeLoanMemo: 'ネット銀行のためつなぎ融資は非対応。土地先行購入の場合は他行との組み合わせが必要。',
    staffMemo: 'ネット銀行最大手。転職直後・自営2期・外国籍OKで属性の幅が広い。全疾病保障が無料なのは業界唯一。審査回答が最短3営業日と速い。',
  },
  {
    id: 'au_var',
    name: 'auじぶん銀行',
    productName: 'じぶんローン（変動）',
    productType: 'variable',
    rate: 0.329,
    danshin: '無料（がん50%保障付）',
    feeYen: 55000,
    guarantee: '不要',
    areas: ['全国'],
    minIncome: 200,
    minYearsEmployed: 1,
    allowedEmployments: ALL_EMP,
    maxLoanRatio: 7,
    features: ['がん保障が無料付帯', 'au回線割引あり', 'ネット完結で手続き簡単'],
    jobChangeMonths: 0,
    selfEmployedYears: 2,
    corporateRepOk: true,
    contractOk: true,
    dispatchOk: false,
    foreignNationalOk: true,
    permanentResidencyRequired: false,
    incomeAggregationOk: true,
    pairLoanOk: true,
    carLoanImpact: '中',
    cardLoanImpact: '高',
    danshinTypes: ['一般団信（無料）', 'がん50%保障（無料）', 'がん100%保障（+0.10%）', '11疾病保障（+0.20%）', '全疾病就業不能保障（+0.30%）'],
    zehDiscount: 0.050,
    longTermQualityDiscount: 0.050,
    webApplicationUrl: 'https://www.jibunbank.co.jp/products/homeloan/',
    paperApplicationUrl: '',
    preScreeningDays: '3〜5営業日',
    bridgeLoanSupport: 'unsupported',
    splitExecutionSupport: 'unsupported',
    landFirstLoanSupport: 'unsupported',
    buildingInterimSupport: 'unsupported',
    repaymentStartTiming: 'final',
    bridgeLoanMemo: 'ネット銀行のためつなぎ融資は非対応。',
    staffMemo: 'auユーザーはさらに0.07%優遇。外国籍・転職直後もOK。がん50%保障が無料で付帯するため保障重視の顧客に強い。',
  },
  {
    id: 'mufg_var',
    name: '三菱UFJ銀行',
    productName: 'ネット住宅ローン（変動）',
    productType: 'variable',
    rate: 0.345,
    danshin: '無料（一般団信）',
    feeYen: 33000,
    guarantee: '不要',
    areas: ['全国'],
    minIncome: 300,
    minYearsEmployed: 3,
    allowedEmployments: REGULAR_EMP,
    maxLoanRatio: 7,
    features: ['メガバンクの安心感', '窓口サポートあり', '総合金融サービスとの連携'],
    jobChangeMonths: 36,
    selfEmployedYears: 3,
    corporateRepOk: false,
    contractOk: false,
    dispatchOk: false,
    foreignNationalOk: true,
    permanentResidencyRequired: true,
    incomeAggregationOk: true,
    pairLoanOk: true,
    carLoanImpact: '高',
    cardLoanImpact: '高',
    danshinTypes: ['一般団信（無料）', 'がん団信（+0.10%）', '7大疾病保障（+0.30%）'],
    zehDiscount: null,
    longTermQualityDiscount: null,
    webApplicationUrl: 'https://www.bk.mufg.jp/kariru/housing/',
    paperApplicationUrl: '',
    preScreeningDays: '3〜5営業日',
    bridgeLoanSupport: 'supported',
    splitExecutionSupport: 'supported',
    landFirstLoanSupport: 'supported',
    buildingInterimSupport: 'supported',
    repaymentStartTiming: 'land',
    bridgeLoanMemo: 'つなぎ融資・分割実行ともに対応。土地先行購入にも対応可能。',
    staffMemo: 'メガバンク最低水準の変動金利。永住権必須・勤続3年以上と条件が厳しい。ただしブランド力で顧客納得感が高い。',
  },
  {
    id: 'paypay_var',
    name: 'PayPay銀行',
    productName: '住宅ローン（変動）',
    productType: 'variable',
    rate: 0.380,
    danshin: '無料（一般団信）',
    feeYen: 33000,
    guarantee: '不要',
    areas: ['全国'],
    minIncome: 200,
    minYearsEmployed: 1,
    allowedEmployments: STABLE_EMP,
    maxLoanRatio: 7,
    features: ['低コストな事務手数料', 'PayPayポイント還元', 'シンプルな手続き'],
    jobChangeMonths: 3,
    selfEmployedYears: 3,
    corporateRepOk: false,
    contractOk: true,
    dispatchOk: false,
    foreignNationalOk: true,
    permanentResidencyRequired: false,
    incomeAggregationOk: true,
    pairLoanOk: true,
    carLoanImpact: '中',
    cardLoanImpact: '高',
    danshinTypes: ['一般団信（無料）', 'がん50%保障（+0.10%）', '11疾病保障（+0.20%）'],
    zehDiscount: null,
    longTermQualityDiscount: null,
    webApplicationUrl: 'https://www.paypay-bank.co.jp/service/loan/homeloan/',
    paperApplicationUrl: '',
    preScreeningDays: '3〜5営業日',
    bridgeLoanSupport: 'unsupported',
    splitExecutionSupport: 'unsupported',
    landFirstLoanSupport: 'unsupported',
    buildingInterimSupport: 'unsupported',
    repaymentStartTiming: 'final',
    bridgeLoanMemo: 'ネット銀行のためつなぎ融資は非対応。',
    staffMemo: 'PayPayユーザーに親和性が高い。事務手数料が安く初期コスト重視の顧客向け。',
  },
  {
    id: 'rakuten_var',
    name: '楽天銀行',
    productName: '住宅ローン（変動）',
    productType: 'variable',
    rate: 0.390,
    danshin: '無料（一般団信）',
    feeYen: 33000,
    guarantee: '不要',
    areas: ['全国'],
    minIncome: 200,
    minYearsEmployed: 1,
    allowedEmployments: STABLE_EMP,
    maxLoanRatio: 7,
    features: ['楽天ポイント還元', '低事務手数料', 'ネット完結申込'],
    jobChangeMonths: 3,
    selfEmployedYears: 3,
    corporateRepOk: false,
    contractOk: true,
    dispatchOk: false,
    foreignNationalOk: true,
    permanentResidencyRequired: false,
    incomeAggregationOk: true,
    pairLoanOk: true,
    carLoanImpact: '中',
    cardLoanImpact: '中',
    danshinTypes: ['一般団信（無料）', 'がん50%保障（+0.10%）', '全疾病就業不能保障（+0.30%）'],
    zehDiscount: null,
    longTermQualityDiscount: 0.025,
    webApplicationUrl: 'https://www.rakuten-bank.co.jp/home-loan/',
    paperApplicationUrl: '',
    preScreeningDays: '3〜5営業日',
    bridgeLoanSupport: 'unsupported',
    splitExecutionSupport: 'unsupported',
    landFirstLoanSupport: 'unsupported',
    buildingInterimSupport: 'unsupported',
    repaymentStartTiming: 'final',
    bridgeLoanMemo: 'ネット銀行のためつなぎ融資は非対応。',
    staffMemo: '楽天経済圏ユーザーに刺さる。ポイント還元が実質金利の引き下げ効果あり。',
  },
  {
    id: 'sony_var',
    name: 'ソニー銀行',
    productName: 'HOME LOAN（変動）',
    productType: 'variable',
    rate: 0.397,
    danshin: '無料（一般団信）',
    feeYen: 44000,
    guarantee: '不要',
    areas: ['全国'],
    minIncome: 200,
    minYearsEmployed: 2,
    allowedEmployments: STABLE_EMP,
    maxLoanRatio: 7,
    features: ['変動↔固定の切替可能', '自己資金10%以上で優遇', '繰上返済手数料無料'],
    jobChangeMonths: 6,
    selfEmployedYears: 3,
    corporateRepOk: false,
    contractOk: true,
    dispatchOk: false,
    foreignNationalOk: true,
    permanentResidencyRequired: false,
    incomeAggregationOk: true,
    pairLoanOk: true,
    carLoanImpact: '中',
    cardLoanImpact: '中',
    danshinTypes: ['一般団信（無料）', 'がん団信（+0.10%）', '生活習慣病団信（+0.20%）'],
    zehDiscount: 0.100,
    longTermQualityDiscount: 0.050,
    webApplicationUrl: 'https://moneykit.net/visitor/hl/',
    paperApplicationUrl: '',
    preScreeningDays: '3〜5営業日',
    bridgeLoanSupport: 'unsupported',
    splitExecutionSupport: 'confirm',
    landFirstLoanSupport: 'confirm',
    buildingInterimSupport: 'confirm',
    repaymentStartTiming: 'final',
    bridgeLoanMemo: 'つなぎ融資は基本非対応。分割実行は要確認。',
    staffMemo: '変動↔固定の切替が自由なのが強み。将来の金利上昇を不安視する顧客に提案しやすい。ZEH優遇が0.10%と業界最大水準。',
  },
  {
    id: 'aeon_var',
    name: 'イオン銀行',
    productName: 'イオン住宅ローン（変動）',
    productType: 'variable',
    rate: 0.430,
    danshin: '無料（一般団信）',
    feeYen: 55000,
    guarantee: '不要',
    areas: ['全国'],
    minIncome: 200,
    minYearsEmployed: 1,
    allowedEmployments: ALL_EMP,
    maxLoanRatio: 7,
    features: ['イオングループ優待', 'WAONポイント還元', '窓口対面サポート'],
    jobChangeMonths: 0,
    selfEmployedYears: 2,
    corporateRepOk: true,
    contractOk: true,
    dispatchOk: true,
    foreignNationalOk: true,
    permanentResidencyRequired: false,
    incomeAggregationOk: true,
    pairLoanOk: true,
    carLoanImpact: '低',
    cardLoanImpact: '中',
    danshinTypes: ['一般団信（無料）', 'がん50%保障（無料）', '全疾病保障（+0.10%）'],
    zehDiscount: 0.050,
    longTermQualityDiscount: 0.050,
    webApplicationUrl: 'https://www.aeonbank.co.jp/homeloan/',
    paperApplicationUrl: '',
    preScreeningDays: '3〜5営業日',
    bridgeLoanSupport: 'unsupported',
    splitExecutionSupport: 'unsupported',
    landFirstLoanSupport: 'unsupported',
    buildingInterimSupport: 'unsupported',
    repaymentStartTiming: 'final',
    bridgeLoanMemo: 'ネット型のためつなぎ融資は非対応。',
    staffMemo: '派遣・パート・外国籍すべてOK。審査が柔軟で属性が弱い顧客の選択肢として重宝する。',
  },
  {
    id: 'mizuho_var',
    name: 'みずほ銀行',
    productName: 'みずほ住宅ローン（変動）',
    productType: 'variable',
    rate: 0.475,
    danshin: '無料（一般団信）',
    feeYen: 33000,
    guarantee: '不要',
    areas: ['全国'],
    minIncome: 300,
    minYearsEmployed: 3,
    allowedEmployments: REGULAR_EMP,
    maxLoanRatio: 6,
    features: ['みずほ銀行口座連携', '窓口サポート充実', '給与振込割引あり'],
    jobChangeMonths: 36,
    selfEmployedYears: null,
    corporateRepOk: false,
    contractOk: false,
    dispatchOk: false,
    foreignNationalOk: true,
    permanentResidencyRequired: true,
    incomeAggregationOk: true,
    pairLoanOk: true,
    carLoanImpact: '高',
    cardLoanImpact: '高',
    danshinTypes: ['一般団信（無料）', 'がん団信（+0.10%）', '8大疾病保障（+0.30%）'],
    zehDiscount: null,
    longTermQualityDiscount: null,
    webApplicationUrl: 'https://www.mizuhobank.co.jp/loan/homeloan/',
    paperApplicationUrl: '',
    preScreeningDays: '3〜5営業日',
    bridgeLoanSupport: 'supported',
    splitExecutionSupport: 'supported',
    landFirstLoanSupport: 'supported',
    buildingInterimSupport: 'supported',
    repaymentStartTiming: 'land',
    bridgeLoanMemo: 'つなぎ融資・分割実行ともに対応。土地購入からの一貫サポートが可能。',
    staffMemo: '正社員・公務員専用。給与振込先がみずほの既存客に提案しやすい。審査基準が厳しく属性の良い顧客向け。',
  },
  {
    id: 'smbc_var',
    name: '三井住友銀行',
    productName: 'SMBCネット住宅ローン（変動）',
    productType: 'variable',
    rate: 0.475,
    danshin: '無料（一般団信）',
    feeYen: 33000,
    guarantee: '不要',
    areas: ['全国'],
    minIncome: 300,
    minYearsEmployed: 3,
    allowedEmployments: REGULAR_EMP,
    maxLoanRatio: 6,
    features: ['Oliveとの連携優遇', 'ブランド力で顧客安心感', '三井住友カード連携'],
    jobChangeMonths: 36,
    selfEmployedYears: null,
    corporateRepOk: false,
    contractOk: false,
    dispatchOk: false,
    foreignNationalOk: true,
    permanentResidencyRequired: true,
    incomeAggregationOk: true,
    pairLoanOk: true,
    carLoanImpact: '高',
    cardLoanImpact: '高',
    danshinTypes: ['一般団信（無料）', 'がん団信（+0.10%）', '7大疾病保障（+0.30%）'],
    zehDiscount: null,
    longTermQualityDiscount: null,
    webApplicationUrl: 'https://www.smbc.co.jp/kojin/loan/homeloan/',
    paperApplicationUrl: '',
    preScreeningDays: '3〜5営業日',
    bridgeLoanSupport: 'supported',
    splitExecutionSupport: 'supported',
    landFirstLoanSupport: 'supported',
    buildingInterimSupport: 'supported',
    repaymentStartTiming: 'land',
    bridgeLoanMemo: 'つなぎ融資・分割実行ともに対応。',
    staffMemo: 'Olive会員はさらに優遇あり。正社員・公務員限定。みずほと同等の厳しさだがブランド選好の顧客に刺さる。',
  },

  // ── 固定金利 ────────────────────────────────────────────────────────────────

  {
    id: 'au_fixed10',
    name: 'auじぶん銀行',
    productName: 'じぶんローン（固定10年）',
    productType: 'fixed',
    fixedPeriod: 'fixed10',
    rate: 1.150,
    danshin: '無料（がん50%保障付）',
    feeYen: 55000,
    guarantee: '不要',
    areas: ['全国'],
    minIncome: 200,
    minYearsEmployed: 1,
    allowedEmployments: ALL_EMP,
    maxLoanRatio: 7,
    features: ['固定10年業界最低水準', 'がん保障が無料', 'au回線割引あり'],
    jobChangeMonths: 0,
    selfEmployedYears: 2,
    corporateRepOk: true,
    contractOk: true,
    dispatchOk: false,
    foreignNationalOk: true,
    permanentResidencyRequired: false,
    incomeAggregationOk: true,
    pairLoanOk: true,
    carLoanImpact: '中',
    cardLoanImpact: '高',
    danshinTypes: ['一般団信（無料）', 'がん50%保障（無料）', 'がん100%保障（+0.10%）', '11疾病保障（+0.20%）'],
    zehDiscount: 0.050,
    longTermQualityDiscount: 0.050,
    webApplicationUrl: 'https://www.jibunbank.co.jp/products/homeloan/',
    paperApplicationUrl: '',
    preScreeningDays: '3〜5営業日',
    bridgeLoanSupport: 'unsupported',
    splitExecutionSupport: 'unsupported',
    landFirstLoanSupport: 'unsupported',
    buildingInterimSupport: 'unsupported',
    repaymentStartTiming: 'final',
    bridgeLoanMemo: 'ネット銀行のためつなぎ融資は非対応。',
    staffMemo: '固定10年で業界最安水準。金利上昇リスクを10年間回避したい顧客に最適。',
  },
  {
    id: 'sbi_fixed10',
    name: '住信SBIネット銀行',
    productName: 'ネット専用住宅ローン（固定10年）',
    productType: 'fixed',
    fixedPeriod: 'fixed10',
    rate: 1.190,
    danshin: '無料（全疾病保障付）',
    feeYen: 55000,
    guarantee: '不要',
    areas: ['全国'],
    minIncome: 200,
    minYearsEmployed: 1,
    allowedEmployments: ALL_EMP,
    maxLoanRatio: 7,
    features: ['全疾病保障が無料', '固定10年も低水準', '審査スピードが速い'],
    jobChangeMonths: 0,
    selfEmployedYears: 2,
    corporateRepOk: true,
    contractOk: true,
    dispatchOk: false,
    foreignNationalOk: true,
    permanentResidencyRequired: false,
    incomeAggregationOk: true,
    pairLoanOk: true,
    carLoanImpact: '中',
    cardLoanImpact: '高',
    danshinTypes: ['一般団信（無料）', '全疾病保障（無料）', 'がん診断給付金（+0.10%）', 'がん100%保障（+0.20%）', '11疾病保障（+0.30%）'],
    zehDiscount: 0.050,
    longTermQualityDiscount: 0.050,
    webApplicationUrl: 'https://www.netbk.co.jp/contents/lineup/homeloan/',
    paperApplicationUrl: '',
    preScreeningDays: '最短3営業日',
    bridgeLoanSupport: 'unsupported',
    splitExecutionSupport: 'unsupported',
    landFirstLoanSupport: 'unsupported',
    buildingInterimSupport: 'unsupported',
    repaymentStartTiming: 'final',
    bridgeLoanMemo: 'ネット銀行のためつなぎ融資は非対応。',
    staffMemo: '全疾病保障付きで固定10年も低水準。変動と固定で迷う顧客に両方提示できる。',
  },
  {
    id: 'aeon_fixed10',
    name: 'イオン銀行',
    productName: 'イオン住宅ローン（固定10年）',
    productType: 'fixed',
    fixedPeriod: 'fixed10',
    rate: 1.290,
    danshin: '無料（一般団信）',
    feeYen: 55000,
    guarantee: '不要',
    areas: ['全国'],
    minIncome: 200,
    minYearsEmployed: 1,
    allowedEmployments: ALL_EMP,
    maxLoanRatio: 7,
    features: ['イオングループ優待', '審査が柔軟', 'WAONポイント還元'],
    jobChangeMonths: 0,
    selfEmployedYears: 2,
    corporateRepOk: true,
    contractOk: true,
    dispatchOk: true,
    foreignNationalOk: true,
    permanentResidencyRequired: false,
    incomeAggregationOk: true,
    pairLoanOk: true,
    carLoanImpact: '低',
    cardLoanImpact: '中',
    danshinTypes: ['一般団信（無料）', 'がん50%保障（無料）', '全疾病保障（+0.10%）'],
    zehDiscount: 0.050,
    longTermQualityDiscount: 0.050,
    webApplicationUrl: 'https://www.aeonbank.co.jp/homeloan/',
    paperApplicationUrl: '',
    preScreeningDays: '3〜5営業日',
    bridgeLoanSupport: 'unsupported',
    splitExecutionSupport: 'unsupported',
    landFirstLoanSupport: 'unsupported',
    buildingInterimSupport: 'unsupported',
    repaymentStartTiming: 'final',
    bridgeLoanMemo: 'ネット型のためつなぎ融資は非対応。',
    staffMemo: '属性が弱い顧客でも固定で安心感を提供できる。審査柔軟性が最大の強み。',
  },
  {
    id: 'rakuten_fixed10',
    name: '楽天銀行',
    productName: '住宅ローン（固定10年）',
    productType: 'fixed',
    fixedPeriod: 'fixed10',
    rate: 1.300,
    danshin: '無料（一般団信）',
    feeYen: 33000,
    guarantee: '不要',
    areas: ['全国'],
    minIncome: 200,
    minYearsEmployed: 1,
    allowedEmployments: STABLE_EMP,
    maxLoanRatio: 7,
    features: ['楽天ポイント還元', '低事務手数料', '固定でも低水準'],
    jobChangeMonths: 3,
    selfEmployedYears: 3,
    corporateRepOk: false,
    contractOk: true,
    dispatchOk: false,
    foreignNationalOk: true,
    permanentResidencyRequired: false,
    incomeAggregationOk: true,
    pairLoanOk: true,
    carLoanImpact: '中',
    cardLoanImpact: '中',
    danshinTypes: ['一般団信（無料）', 'がん50%保障（+0.10%）', '全疾病就業不能保障（+0.30%）'],
    zehDiscount: null,
    longTermQualityDiscount: 0.025,
    webApplicationUrl: 'https://www.rakuten-bank.co.jp/home-loan/',
    paperApplicationUrl: '',
    preScreeningDays: '3〜5営業日',
    bridgeLoanSupport: 'unsupported',
    splitExecutionSupport: 'unsupported',
    landFirstLoanSupport: 'unsupported',
    buildingInterimSupport: 'unsupported',
    repaymentStartTiming: 'final',
    bridgeLoanMemo: 'ネット銀行のためつなぎ融資は非対応。',
    staffMemo: '固定でも事務手数料が低く初期コストを抑えたい顧客に最適。楽天経済圏ユーザーに刺さる。',
  },
  {
    id: 'paypay_fixed10',
    name: 'PayPay銀行',
    productName: '住宅ローン（固定10年）',
    productType: 'fixed',
    fixedPeriod: 'fixed10',
    rate: 1.340,
    danshin: '無料（一般団信）',
    feeYen: 33000,
    guarantee: '不要',
    areas: ['全国'],
    minIncome: 200,
    minYearsEmployed: 1,
    allowedEmployments: STABLE_EMP,
    maxLoanRatio: 7,
    features: ['低コストな事務手数料', 'PayPayポイント還元', 'シンプルな手続き'],
    jobChangeMonths: 3,
    selfEmployedYears: 3,
    corporateRepOk: false,
    contractOk: true,
    dispatchOk: false,
    foreignNationalOk: true,
    permanentResidencyRequired: false,
    incomeAggregationOk: true,
    pairLoanOk: true,
    carLoanImpact: '中',
    cardLoanImpact: '高',
    danshinTypes: ['一般団信（無料）', 'がん50%保障（+0.10%）', '11疾病保障（+0.20%）'],
    zehDiscount: null,
    longTermQualityDiscount: null,
    webApplicationUrl: 'https://www.paypay-bank.co.jp/service/loan/homeloan/',
    paperApplicationUrl: '',
    preScreeningDays: '3〜5営業日',
    bridgeLoanSupport: 'unsupported',
    splitExecutionSupport: 'unsupported',
    landFirstLoanSupport: 'unsupported',
    buildingInterimSupport: 'unsupported',
    repaymentStartTiming: 'final',
    bridgeLoanMemo: 'ネット銀行のためつなぎ融資は非対応。',
    staffMemo: '固定でも事務手数料が低い。PayPayユーザーへの提案でネット銀行への親しみを活かせる。',
  },
  {
    id: 'mizuho_fixed10',
    name: 'みずほ銀行',
    productName: 'みずほ住宅ローン（固定10年）',
    productType: 'fixed',
    fixedPeriod: 'fixed10',
    rate: 1.350,
    danshin: '無料（一般団信）',
    feeYen: 33000,
    guarantee: '不要',
    areas: ['全国'],
    minIncome: 300,
    minYearsEmployed: 3,
    allowedEmployments: REGULAR_EMP,
    maxLoanRatio: 6,
    features: ['メガバンクの安心感', '窓口サポート充実', '固定期間後の優遇あり'],
    jobChangeMonths: 36,
    selfEmployedYears: null,
    corporateRepOk: false,
    contractOk: false,
    dispatchOk: false,
    foreignNationalOk: true,
    permanentResidencyRequired: true,
    incomeAggregationOk: true,
    pairLoanOk: true,
    carLoanImpact: '高',
    cardLoanImpact: '高',
    danshinTypes: ['一般団信（無料）', 'がん団信（+0.10%）', '8大疾病保障（+0.30%）'],
    zehDiscount: null,
    longTermQualityDiscount: null,
    webApplicationUrl: 'https://www.mizuhobank.co.jp/loan/homeloan/',
    paperApplicationUrl: '',
    preScreeningDays: '3〜5営業日',
    bridgeLoanSupport: 'supported',
    splitExecutionSupport: 'supported',
    landFirstLoanSupport: 'supported',
    buildingInterimSupport: 'supported',
    repaymentStartTiming: 'land',
    bridgeLoanMemo: 'つなぎ融資・分割実行ともに対応。',
    staffMemo: '属性が良い顧客で固定の安心感も求める場合に。正社員・公務員限定。',
  },
  {
    id: 'sony_fixed10',
    name: 'ソニー銀行',
    productName: 'HOME LOAN（固定10年）',
    productType: 'fixed',
    fixedPeriod: 'fixed10',
    rate: 1.380,
    danshin: '無料（一般団信）',
    feeYen: 44000,
    guarantee: '不要',
    areas: ['全国'],
    minIncome: 200,
    minYearsEmployed: 2,
    allowedEmployments: STABLE_EMP,
    maxLoanRatio: 7,
    features: ['固定↔変動の切替可能', 'ZEH優遇が手厚い', '繰上返済手数料無料'],
    jobChangeMonths: 6,
    selfEmployedYears: 3,
    corporateRepOk: false,
    contractOk: true,
    dispatchOk: false,
    foreignNationalOk: true,
    permanentResidencyRequired: false,
    incomeAggregationOk: true,
    pairLoanOk: true,
    carLoanImpact: '中',
    cardLoanImpact: '中',
    danshinTypes: ['一般団信（無料）', 'がん団信（+0.10%）', '生活習慣病団信（+0.20%）'],
    zehDiscount: 0.100,
    longTermQualityDiscount: 0.050,
    webApplicationUrl: 'https://moneykit.net/visitor/hl/',
    paperApplicationUrl: '',
    preScreeningDays: '3〜5営業日',
    bridgeLoanSupport: 'unsupported',
    splitExecutionSupport: 'confirm',
    landFirstLoanSupport: 'confirm',
    buildingInterimSupport: 'confirm',
    repaymentStartTiming: 'final',
    bridgeLoanMemo: 'つなぎ融資は基本非対応。分割実行は要確認。',
    staffMemo: '固定から変動への切替ができるため、将来の状況変化に柔軟に対応できる。ZEH・長期優良の優遇が業界最高水準。',
  },
  {
    id: 'smbc_fixed10',
    name: '三井住友銀行',
    productName: 'SMBCネット住宅ローン（固定10年）',
    productType: 'fixed',
    fixedPeriod: 'fixed10',
    rate: 1.460,
    danshin: '無料（一般団信）',
    feeYen: 33000,
    guarantee: '不要',
    areas: ['全国'],
    minIncome: 300,
    minYearsEmployed: 3,
    allowedEmployments: REGULAR_EMP,
    maxLoanRatio: 6,
    features: ['Oliveとの連携優遇', 'ブランド力', '固定期間後の優遇あり'],
    jobChangeMonths: 36,
    selfEmployedYears: null,
    corporateRepOk: false,
    contractOk: false,
    dispatchOk: false,
    foreignNationalOk: true,
    permanentResidencyRequired: true,
    incomeAggregationOk: true,
    pairLoanOk: true,
    carLoanImpact: '高',
    cardLoanImpact: '高',
    danshinTypes: ['一般団信（無料）', 'がん団信（+0.10%）', '7大疾病保障（+0.30%）'],
    zehDiscount: null,
    longTermQualityDiscount: null,
    webApplicationUrl: 'https://www.smbc.co.jp/kojin/loan/homeloan/',
    paperApplicationUrl: '',
    preScreeningDays: '3〜5営業日',
    bridgeLoanSupport: 'supported',
    splitExecutionSupport: 'supported',
    landFirstLoanSupport: 'supported',
    buildingInterimSupport: 'supported',
    repaymentStartTiming: 'land',
    bridgeLoanMemo: 'つなぎ融資・分割実行ともに対応。',
    staffMemo: '正社員・公務員限定。固定でもブランド選好の顧客に対応。',
  },
  {
    id: 'mufg_fixed10',
    name: '三菱UFJ銀行',
    productName: 'ネット住宅ローン（固定10年）',
    productType: 'fixed',
    fixedPeriod: 'fixed10',
    rate: 1.500,
    danshin: '無料（一般団信）',
    feeYen: 33000,
    guarantee: '不要',
    areas: ['全国'],
    minIncome: 300,
    minYearsEmployed: 3,
    allowedEmployments: REGULAR_EMP,
    maxLoanRatio: 7,
    features: ['メガバンクの安心感', '総合金融サービスとの連携', '窓口サポートあり'],
    jobChangeMonths: 36,
    selfEmployedYears: 3,
    corporateRepOk: false,
    contractOk: false,
    dispatchOk: false,
    foreignNationalOk: true,
    permanentResidencyRequired: true,
    incomeAggregationOk: true,
    pairLoanOk: true,
    carLoanImpact: '高',
    cardLoanImpact: '高',
    danshinTypes: ['一般団信（無料）', 'がん団信（+0.10%）', '7大疾病保障（+0.30%）'],
    zehDiscount: null,
    longTermQualityDiscount: null,
    webApplicationUrl: 'https://www.bk.mufg.jp/kariru/housing/',
    paperApplicationUrl: '',
    preScreeningDays: '3〜5営業日',
    bridgeLoanSupport: 'supported',
    splitExecutionSupport: 'supported',
    landFirstLoanSupport: 'supported',
    buildingInterimSupport: 'supported',
    repaymentStartTiming: 'land',
    bridgeLoanMemo: 'つなぎ融資・分割実行ともに対応。',
    staffMemo: 'メガバンク固定10年。属性の良い顧客で安定志向の方に。',
  },
  {
    id: 'aruhi_flat35',
    name: 'フラット35（ARUHI）',
    productName: 'フラット35（全期間固定）',
    productType: 'fixed',
    fixedPeriod: 'flat35',
    rate: 1.820,
    danshin: '任意（別途加入）',
    feeYen: 11000,
    guarantee: '不要（機構保証）',
    areas: ['全国'],
    minIncome: 0,
    minYearsEmployed: 0,
    allowedEmployments: ALL_EMP,
    maxLoanRatio: 8,
    features: ['全期間固定で金利変動リスクなし', '雇用形態・年収制限なし', '自営業・パートも申込可'],
    jobChangeMonths: 0,
    selfEmployedYears: null,
    corporateRepOk: true,
    contractOk: true,
    dispatchOk: true,
    foreignNationalOk: true,
    permanentResidencyRequired: false,
    incomeAggregationOk: true,
    pairLoanOk: false,
    carLoanImpact: '低',
    cardLoanImpact: '低',
    danshinTypes: ['団信は任意（月払いで加入可）', '機構団信（+0.28%相当）'],
    zehDiscount: 0.250,
    longTermQualityDiscount: 0.250,
    webApplicationUrl: 'https://www.aruhi-corp.co.jp/service/flat35/',
    paperApplicationUrl: '',
    preScreeningDays: '5〜7営業日',
    bridgeLoanSupport: 'unsupported',
    splitExecutionSupport: 'supported',
    landFirstLoanSupport: 'unsupported',
    buildingInterimSupport: 'supported',
    repaymentStartTiming: 'final',
    bridgeLoanMemo: 'つなぎ融資は非対応。分割実行は対応（建物完成後に一括実行が基本だが段階融資あり）。',
    splitExecutionMemo: 'フラット35は段階融資制度あり。中間金への対応が可能。',
    staffMemo: '属性不問が最大の強み。フリーランス・パート・転職直後の顧客も申込可能。ZEH・長期優良住宅は0.25%引きで業界断トツ。全期間固定なので将来の金利上昇を完全にヘッジできる。団信が任意加入なので健康問題がある顧客にも選択肢となる。',
  },
];
